String defaultProfilePhoto =
    "https://firebasestorage.googleapis.com/v0/b/foodmood-af335.appspot.com/o/default%2Fdefault-profile-picture.jpeg?alt=media&token=889b4155-b10b-44e1-b987-30d739def69b";

List<Map<String, dynamic>> gifts = [
  {
    "giftName": "Ümumi",
    "moodx": 8,
    "image": "assets/salad.png",
    "level": 1,
    "giftId": 11,
  },
  {
    "giftName": "Güllər",
    "moodx": 10,
    "image": "assets/gifts/flowers/flower2-min.png",
    "level": 2,
    "giftId": 21,
  },
  {
    "giftName": "Güllər",
    "moodx": 14,
    "image": "assets/gifts/flowers/plumeria-min.png",
    "level": 2,
    "giftId": 22,
  },
  {
    "giftName": "Güllər",
    "moodx": 18,
    "image": "assets/gifts/flowers/african.png",
    "level": 2,
    "giftId": 23,
  },
  {
    "giftName": "Güllər",
    "moodx": 20,
    "image": "assets/gifts/flowers/acanthaceae.png",
    "level": 2,
    "giftId": 24,
  },
  {
    "giftName": "Güllər",
    "moodx": 28,
    "image": "assets/gifts/flowers/black.png",
    "level": 2,
    "giftId": 25,
  },
  {
    "giftName": "Güllər",
    "moodx": 40,
    "image": "assets/gifts/flowers/flax.png",
    "level": 2,
    "giftId": 26,
  },
  {
    "giftName": "Güllər",
    "moodx": 56,
    "image": "assets/gifts/flowers/flower.png",
    "level": 2,
    "giftId": 27,
  },
  {
    "giftName": "Güllər",
    "moodx": 70,
    "image": "assets/gifts/flowers/pink-cosmos.png",
    "level": 2,
    "giftId": 28,
  },
  {
    "giftName": "Güllər",
    "moodx": 88,
    "image": "assets/gifts/flowers/amaryllis.png",
    "level": 2,
    "giftId": 29,
  },
  {
    "giftName": "Güllər",
    "moodx": 100,
    "image": "assets/gifts/flowers/pansy-min.png",
    "level": 2,
    "giftId": 210,
  },
  {
    "giftName": "Güllər",
    "moodx": 200,
    "image": "assets/gifts/flowers/rose2-min.png",
    "level": 2,
    "giftId": 211,
  },
  {
    "giftName": "Güllər",
    "moodx": 240,
    "image": "assets/gifts/flowers/bougainvillea.png",
    "level": 2,
    "giftId": 212,
  },
  {
    "giftName": "Güllər",
    "moodx": 400,
    "image": "assets/gifts/flowers/sabi.png",
    "level": 2,
    "giftId": 213,
  },
  {
    "giftName": "Güllər",
    "moodx": 550,
    "image": "assets/gifts/flowers/gallardia.png",
    "level": 2,
    "giftId": 214,
  },
  {
    "giftName": "Güllər",
    "moodx": 1000,
    "image": "assets/gifts/flowers/hoya.png",
    "level": 2,
    "giftId": 215,
  },
  {
    "giftName": "Güllər",
    "moodx": 3000,
    "image": "assets/gifts/flowers/lotus-min.png",
    "level": 2,
    "giftId": 216,
  },
  {
    "giftName": "Güllər",
    "moodx": 5000,
    "image": "assets/gifts/flowers/chysanthemum.png",
    "level": 2,
    "giftId": 217,
  },
  {
    "giftName": "Güllər",
    "moodx": 6000,
    "image": "assets/gifts/flowers/peony-min.png",
    "level": 2,
    "giftId": 218,
  },
  {
    "giftName": "Güllər",
    "moodx": 8000,
    "image": "assets/gifts/flowers/rose-min.png",
    "level": 2,
    "giftId": 219,
  },
  {
    "giftName": "Güllər",
    "moodx": 9000,
    "image": "assets/gifts/flowers/jade.png",
    "level": 2,
    "giftId": 220,
  },
  {
    "giftName": "Güllər",
    "moodx": 15000,
    "image": "assets/gifts/flowers/hibiscus.png",
    "level": 2,
    "giftId": 221,
  },
  {
    "giftName": "Güllər",
    "moodx": 25000,
    "image": "assets/gifts/flowers/dahlia.png",
    "level": 2,
    "giftId": 222,
  },
  {
    "giftName": "Güllər",
    "moodx": 50000,
    "image": "assets/gifts/flowers/gardenia-min.png",
    "level": 2,
    "giftId": 223,
  },
  {
    "giftName": "Güllər",
    "moodx": 100000,
    "image": "assets/gifts/flowers/rose.png",
    "level": 2,
    "giftId": 224,
  },
  {
    "giftName": "İçkilər",
    "moodx": 8,
    "image": "assets/gifts/drinks/tea2.png",
    "level": 3,
    "giftId": 31,
  },
  {
    "giftName": "İçkilər",
    "moodx": 12,
    "image": "assets/gifts/drinks/green-tea.png",
    "level": 3,
    "giftId": 32,
  },
  {
    "giftName": "İçkilər",
    "moodx": 14,
    "image": "assets/gifts/drinks/coffee-cup2.png",
    "level": 3,
    "giftId": 33,
  },
  {
    "giftName": "İçkilər",
    "moodx": 18,
    "image": "assets/gifts/drinks/coffee-cup.png",
    "level": 3,
    "giftId": 34,
  },
  {
    "giftName": "İçkilər",
    "moodx": 20,
    "image": "assets/gifts/drinks/hot-chocolate.png",
    "level": 3,
    "giftId": 35,
  },
  {
    "giftName": "İçkilər",
    "moodx": 24,
    "image": "assets/gifts/drinks/soda2.png",
    "level": 3,
    "giftId": 36,
  },
  {
    "giftName": "İçkilər",
    "moodx": 28,
    "image": "assets/gifts/drinks/energy-drink.png",
    "level": 3,
    "giftId": 37,
  },
  {
    "giftName": "İçkilər",
    "moodx": 30,
    "image": "assets/gifts/drinks/orange-juice2.png",
    "level": 3,
    "giftId": 38,
  },
  {
    "giftName": "İçkilər",
    "moodx": 32,
    "image": "assets/gifts/drinks/juice.png",
    "level": 3,
    "giftId": 39,
  },
  {
    "giftName": "İçkilər",
    "moodx": 34,
    "image": "assets/gifts/drinks/orange-juice.png",
    "level": 3,
    "giftId": 310,
  },
  {
    "giftName": "İçkilər",
    "moodx": 50,
    "image": "assets/gifts/drinks/cocktail4.png",
    "level": 3,
    "giftId": 311,
  },
  {
    "giftName": "İçkilər",
    "moodx": 100,
    "image": "assets/gifts/drinks/cocktails5.png",
    "level": 3,
    "giftId": 312,
  },
  {
    "giftName": "İçkilər",
    "moodx": 120,
    "image": "assets/gifts/drinks/beer.png",
    "level": 3,
    "giftId": 313,
  },
  {
    "giftName": "İçkilər",
    "moodx": 140,
    "image": "assets/gifts/drinks/poinsettia.png",
    "level": 3,
    "giftId": 314,
  },
  {
    "giftName": "İçkilər",
    "moodx": 1000,
    "image": "assets/gifts/drinks/rompope.png",
    "level": 3,
    "giftId": 315,
  },
  {
    "giftName": "İçkilər",
    "moodx": 1200,
    "image": "assets/gifts/drinks/drink3.png",
    "level": 3,
    "giftId": 316,
  },
  {
    "giftName": "İçkilər",
    "moodx": 2000,
    "image": "assets/gifts/drinks/vodka.png",
    "level": 3,
    "giftId": 317,
  },
  {
    "giftName": "İçkilər",
    "moodx": 5000,
    "image": "assets/gifts/drinks/cocktail6.png",
    "level": 3,
    "giftId": 318,
  },
  {
    "giftName": "İçkilər",
    "moodx": 10000,
    "image": "assets/gifts/drinks/cocktail.png",
    "level": 3,
    "giftId": 319,
  },
  {
    "giftName": "İçkilər",
    "moodx": 50000,
    "image": "assets/gifts/drinks/champagne.png",
    "level": 3,
    "giftId": 320,
  },
  {
    "giftName": "İçkilər",
    "moodx": 100000,
    "image": "assets/gifts/drinks/champagne2.png",
    "level": 3,
    "giftId": 321,
  },
];
List foods = [
  {
    "photo": "assets/chicken.png",
    "name": "Toyuq",
    "id": 1,
  },
  {
    "photo": "assets/noodles.png",
    "name": "Şorbalar",
    "id": 2,
  },
  {
    "photo": "assets/salad.png",
    "name": "Vegeteriyan",
    "id": 3,
  },
  {
    "photo": "assets/barbeque.png",
    "name": "Kabab",
    "id": 4,
  },
  {
    "photo": "assets/steak.png",
    "name": "Ət",
    "id": 5,
  },
  {
    "photo": "assets/sushi-2.png",
    "name": "Suşi",
    "id": 6,
  },
  {
    "photo": "assets/fast-food.png",
    "name": "Fast Food",
    "id": 7,
  },
  {
    "photo": "assets/fish.png",
    "name": "Balıq",
    "id": 8,
  },
  {
    "photo": "assets/croissant.png",
    "name": "Xəmir yeməkləri",
    "id": 9,
  }
];
List drinks = [
  {
    "photo": "assets/soda.png",
    "name": "Qazlı içkilər",
    "id": 11,
  },
  {
    "photo": "assets/old-fashion.png",
    "name": "Limonad",
    "id": 12,
  },
  {
    "photo": "assets/coffee-cup.png",
    "name": "Kofe",
    "id": 13,
  },
  {
    "photo": "assets/beer-2.png",
    "name": "Pivə",
    "id": 14,
  },
  {
    "photo": "assets/cocktail.png",
    "name": "Kokteyl",
    "id": 15,
  },
  {
    "photo": "assets/wine-glass.png",
    "name": "Şərab",
    "id": 16,
  },
  {
    "photo": "assets/vodka-2.png",
    "name": "Likor",
    "id": 17,
  },
  {
    "photo": "assets/whiskey-2.png",
    "name": "Viski",
    "id": 18,
  },
  {
    "photo": "assets/tequila.png",
    "name": "Tekilla",
    "id": 19,
  }
];

List restaurant = [
  {
    "photo": "assets/burger-2.png",
    "name": "Fast Food",
    "id": 21,
  },
  {
    "photo": "assets/coffee.png",
    "name": "Kofe Shop",
    "id": 22,
  },
  {
    "photo": "assets/pub.png",
    "name": "Pub",
    "id": 23,
  },
  {
    "photo": "assets/restaurant.png",
    "name": "Restoran",
    "id": 24,
  },
  {
    "photo": "assets/bar.png",
    "name": "Bar",
    "id": 25,
  },
  {
    "photo": "assets/karaoke.png",
    "name": "Karaoke",
    "id": 26,
  },
  {
    "photo": "assets/terrace-2.png",
    "name": "Açıq hava",
    "id": 27,
  },
  {
    "photo": "assets/live-streaming.png",
    "name": "Canlı musiqi",
    "id": 28,
  },
  {
    "photo": "assets/beach.png",
    "name": "Dənizkənarı",
    "id": 29,
  }
];
